### ISSUE TITLE
Support resume of FULL_TABLE replication method when it fails or is interrupted

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise#231]
FULL_TABLE replication is a problem for very large tables since must successfully complete every batch MERGE.

After a failure, the target has a partially populated table, but restarting the replication will start from the beginning and merge records that are already present. This can be a waste of time and money due to repeated attempts to load data that is already present (assuming of course the source data hasn't change between runs).

Since FULL_TABLE is used for the initial population of INCREMENTAL and LOG_BASED replication, this problem potentially effects all large table initial population.

It would be better if FULL_TABLE could resume from failure or interruption and continue where it left off.

**Comment by koszti** [comment]
This makes sense however FULL_TABLE ideally should be done by a new oracle-to-<snowflake|redshift|postgres> component. Singer is not great when doing initial sync on big tables and there are better methods doing that faster.

On the flip sode writing  state files more often to resume failed INCREMENTAL and LOG_BASED replications also would make a lot of sense and something that will arrive very soon.

**Comment by koszti** [comment]
Closing this because saving state file during sync is available for a while for INCREMENTAL and LOG_BASED methods. If INCREMENTAL and LOG_BASED tap-run fails in the middle then the next tap-run will start consuming from latest replicated position.  

Resuming FULL_TABLE or initial syncs is not supported because that could make troubles of capturing a consistent state for the next tap-run:
* in case of LOG_BASED we don't know what happened in the table between the first failed attempt and the resumed sync and we don't know which binlog position we need to start reading from after initial sync
* what if the table structure changed in the meantime?
* what if the column type changed in the meantime?
* what if an UPDATE/DELETE statement ran in the meantime?
