### ISSUE TITLE
Using GKE to run PipelineWise

### ISSUE THREAD

**Issue by stewartbryson** [transferwise/pipelinewise#439]
This is just a question, so I stripped out the template. I hope that's ok.

I'm not hands-on with PipelineWise yet, so forgive the newbie question. I'm considering running individual pipelines as individual pods in a GKE. I doubt Google Cloud Run will work, as it sounds like pipelines are stateful. I just wondered if you had any insight into this area before I gave it a try. Your description under the multi-cluster architecture seemed to imply that state needed to be shared across all pipelines, but I might have misread.

Thank you.

**Comment by koszti** [comment]
You need to mount `~/.pipelinewise` from a shared NFS on each pod. This is currently the tested and recommended approach until PPW doesn't have a backend database to store states of the pipes.

`~/.pipelinewise` is tracking the individual pipeline statuses, states and configurations. Multiple instance of PPW can use the same `~/.pipelinewise` directory in parallel with no issues.

**Comment by EamonKeane** [comment]
Cloud run won't work, no. A simple GKE cronjob can work - you'll need to run two commands:

* pipelinewise import (detect any changes to sources since pipeline last run. Not sure if it's advisable to run this in parallel)
* pipelinewise run_tap (for each source/target combination)

If you want to get more visibility into the process I'd recommend going with airflow with one pipelinewise import and then fan out for each tap.

**Comment by stewartbryson** [comment]
Thanks for your help @EamonKeane and @koszti
